=== kuro91/qDB/tecwebprojbeta/tecwebprojbeta/data/utenti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.localhost"
	xmlns="http://www.localhost"
	elementFormDefault="qualified" >
	
	<xsd:element name="utenti" type="Tutenti" />
	<!-- definizione Tutenti -->
		<xsd:complexType name="Tutenti">
			<xsd:sequence maxOccurs="unbounded">
				<xsd:element name="utente" type="Tutente" />
			</xsd:sequence>
		</xsd:complexType>
		<!-- definizione Tutente -->
		<xsd:complexType name="Tutente">
			<xsd:sequence>
				<xsd:element name="username" type="xsd:string" />
				<xsd:element name="useremail" type="xsd:string" />
				<xsd:element name="password" type="xsd:string" />
				<xsd:element name="tipo" type="Ttipo" />
			</xsd:sequence>
		</xsd:complexType>
		<!-- definizione Ttipo -->
		<xsd:simpleType name="Ttipo">
			<xsd:restriction base="xsd:string">
				<xsd:enumeration value="admin"/>
				<xsd:enumeration value="user"/>
			</xsd:restriction>
		</xsd:simpleType>
</xsd:schema>

=== kuro91/qDB/tecwebprojbeta/tecwebprojbeta/data/utenti.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="utenti.xsl"?>
<utenti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="utenti.xsd">
	<utente>
		<username>damarin</username>
		<useremail>damarin82@gmail.com</useremail>
		<password>1234</password>
		<tipo>admin</tipo>
	</utente>
	<utente>
		<username>gigio</username>
		<useremail>gigio@pippo.it</useremail>
		<password>2222</password>
		<tipo>user</tipo>
	</utente>
</utenti>
